MVC/Controllers/BugController.cs
using System;
using System.Collections.Generic;

using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC.Data;
using MVC.Models;

namespace MVC.Controllers
{
    public class BugController : Controller
    {
        private BugDatabaseEntities1 db = new BugDatabaseEntities1();



        
        // GET: Bug
        public ActionResult Index()
        {

            calcount(); //Get Total Count of Sql Data
            calHighRisk();

            var sqlDataList = Fetch();

            
            

            //var sqlData = FetchOne();

            return View("Index", sqlDataList);



            //return View(db.Table_1.ToList());
        }

      


        public ActionResult SearchButtonHandle(int id)
        {

            calcount(); //Get Total Count of Sql Data

            SqlFetch data = new SqlFetch();

            Table_1 obj = data.FetchOne(id);

            

            return View("Search", obj);

        }

        [HttpPost]
        public ActionResult SearchButtonHandle(FormCollection form)
        {

            ViewBag.test = form["SearchInput"];

            SqlFetch data = new SqlFetch();

            int numericValue;

            if (int.TryParse(ViewBag.test, out numericValue))
            {
                Table_1 obj = data.FetchOne(Int32.Parse(ViewBag.test));
                return View("Search", obj);

            }
            else
            {

                List<Table_1> list = new List<Table_1>();
                return View("Index", list);
            }

            



           

        }


        // GET: Bug/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Table_1 table_1 = db.Table_1.Find(id);
            if (table_1 == null)
            {
                return HttpNotFound();
            }
            return View(table_1);
        }

        // GET: Bug/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Bug/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Date,Bug_Level")] Table_1 table_1)
        {
            if (ModelState.IsValid)
            {
                db.Table_1.Add(table_1);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(table_1);
        }

        // GET: Bug/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Table_1 table_1 = db.Table_1.Find(id);
            if (table_1 == null)
            {
                return HttpNotFound();
            }
            return View(table_1);
        }

        // POST: Bug/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Date")] Table_1 table_1)
        {
            if (ModelState.IsValid)
            {
                db.Entry(table_1).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(table_1);
        }

        // GET: Bug/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Table_1 table_1 = db.Table_1.Find(id);
            if (table_1 == null)
            {
                return HttpNotFound();
            }
            return View(table_1);
        }

        // POST: Bug/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Table_1 table_1 = db.Table_1.Find(id);
            db.Table_1.Remove(table_1);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        public void calcount()
        {
            ViewBag.Count = db.Table_1.Count();
            
            
        }

        public void calHighRisk()
        {

            SqlFetch data = new SqlFetch();


            ViewBag.AmtHR = data.FetchHRAmt();
        }

        public List<Table_1> Fetch()
        {
            List<Table_1> dataObject = new List<Table_1>();

            SqlFetch data = new SqlFetch();

            dataObject = data.Fetch();

            return dataObject;
        }


        


    }
}

MVC/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class UploadController : Controller
    {
        // GET: Upload
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult UploadFile()
        {
            return View();
        }
        [HttpPost]
        public ActionResult UploadFile(HttpPostedFileBase file)
        {
            try
            {
                if (file.ContentLength > 0)
                {
                    string _FileName = Path.GetFileName(file.FileName);
                    string _path = Path.Combine(Server.MapPath("~/UploadedFiles"), _FileName);
                    file.SaveAs(_path);
                    ViewBag.Message = "File Uploaded Successfully!!";
                }
             
                
                return View();
            }
            catch
            {
                ViewBag.Message = "File upload failed!!";
                return View();
            }
        }
    }
}

MVC/Views/Upload/UploadFile.cshtml
@{
    ViewBag.Title = "UploadFile";
    Layout = null;
}



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <style>

        a {
            text-decoration: none;
        }

        body {
            margin-top: 0;
            margin-left: 0;
        }
        /* Split the screen in half */
        .split {
            position: fixed;
            z-index: 1;
            top: 0;
            overflow-x: hidden;
        }

        .Top {
            z-index: 3;
            width: 100%;
            height: 10%;
            position: fixed;
            background: greenyellow;
        }

        /* Control the left side */
        .Nav {
            z-index: 2;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            left: 0;
            width: 13%;
            height: 100%;
            background-color: #111;
            margin-top: 3em;
            color: white;
        }

        .Nav_Head {
        }

        .Nav_Action_List {
            list-style: none;
        }


        /* Control the right side */
        .Content {
            display: flex;
            align-items: center;
            justify-content: right;
            float: left;
            width: 100%;
            right: 0;
            height: 100%;
            background-color: dimgrey;
        }
    </style>
    <title>Index</title>
</head>
<body>

    <div class="Top">

        <h1>Dashboard</h1>

    </div>


    <div class="Nav split">
        <div class="Nav_Head">
            <h3>Welcome Dino</h3>
            @*<h3> Welcome @Session["userName"].ToString()</h3>*@
        </div>
        <div class="Nav_Action">


            <ul class="Nav_Action_List">
                <li><a href="@Url.Action("Index","Bug")"><h3>View Bug Report</h2></a></li>
                <li><a href="@Url.Action("Regist","Home")"><h3>Register</h3></a></li>
                <li><a href="@Url.Action("LogOut","Login")"><h3>Log Out</h3></a></li>
            </ul>




        </div>




    </div>

    <div class="Content split">


        <h2>UploadFile</h2>
        @using (Html.BeginForm("UploadFile", "Upload", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div>
                @Html.TextBox("file", "", new { type = "file" }) <br />
                <input type="submit" value="Upload" />
                @ViewBag.Message
            </div>
        }

    </div>
</body>
</html>