MVC/Models/User.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public int UserID { get; set; }

        [DisplayName("User Name")]
        [Required(ErrorMessage ="This field is required.")]
        public string UserName { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This field is required.")]
        public string Password { get; set; }


        [DataType(DataType.Password)]
        [DisplayName("Confirm Password")]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }

        [Required(ErrorMessage = "This field is required.")]
        public Nullable<bool> isAdmin { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}

MVC/Controllers/BugController.cs
using System;
using System.Collections.Generic;

using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC.Data;
using MVC.Models;

namespace MVC.Controllers
{
    public class BugController : Controller
    {
        private BugDatabaseEntities1 db = new BugDatabaseEntities1();



        
        // GET: Bug
        public ActionResult Index()
        {

            calcount(); //Get Total Count of Sql Data
            calHighRisk();

            var sqlDataList = Fetch();

            
            

            //var sqlData = FetchOne();

            return View("Index", sqlDataList);



            //return View(db.Table_1.ToList());
        }

      


        public ActionResult SearchButtonHandle(int id)
        {

            calcount(); //Get Total Count of Sql Data

            SqlFetch data = new SqlFetch();

            Table_1 obj = data.FetchOne(id);

            

            return View("Search", obj);

        }

        [HttpPost]
        public ActionResult SearchButtonHandle(FormCollection form)
        {

            ViewBag.test = form["SearchInput"];

            SqlFetch data = new SqlFetch();

            int numericValue;

            if (int.TryParse(ViewBag.test, out numericValue))
            {
                Table_1 obj = data.FetchOne(Int32.Parse(ViewBag.test));
                return View("Search", obj);

            }
            else
            {

                List<Table_1> list = new List<Table_1>();
                return View("Index", list);
            }

            



           

        }


        // GET: Bug/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Table_1 table_1 = db.Table_1.Find(id);
            if (table_1 == null)
            {
                return HttpNotFound();
            }
            return View(table_1);
        }

        // GET: Bug/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Bug/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Date,Bug_Level")] Table_1 table_1)
        {
            if (ModelState.IsValid)
            {
                db.Table_1.Add(table_1);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(table_1);
        }

        // GET: Bug/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Table_1 table_1 = db.Table_1.Find(id);
            if (table_1 == null)
            {
                return HttpNotFound();
            }
            return View(table_1);
        }

        // POST: Bug/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Date")] Table_1 table_1)
        {
            if (ModelState.IsValid)
            {
                db.Entry(table_1).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(table_1);
        }

        // GET: Bug/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Table_1 table_1 = db.Table_1.Find(id);
            if (table_1 == null)
            {
                return HttpNotFound();
            }
            return View(table_1);
        }

        // POST: Bug/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Table_1 table_1 = db.Table_1.Find(id);
            db.Table_1.Remove(table_1);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        public void calcount()
        {
            ViewBag.Count = db.Table_1.Count();
            
            
        }

        public void calHighRisk()
        {

            SqlFetch data = new SqlFetch();


            ViewBag.AmtHR = data.FetchHRAmt();
        }

        public List<Table_1> Fetch()
        {
            List<Table_1> dataObject = new List<Table_1>();

            SqlFetch data = new SqlFetch();

            dataObject = data.Fetch();

            return dataObject;
        }


        


    }
}

MVC/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC.Models;

namespace MVC.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        [HttpGet]
        public ActionResult AddOrEdit(int id=0)
        {
            User userModel = new User();
            return View(userModel);
        }

        [HttpPost]
        public ActionResult AddOrEdit(User userModel)
        {
            using(LoginDBEntities db = new LoginDBEntities())
            {

                if(db.Users.Any(x => x.UserName == userModel.UserName))
                {
                    ViewBag.DuplicateMessage = "Username Existed";
                    return View("AddOredit", userModel);
                }

                db.Users.Add(userModel);
                db.SaveChanges();
            }
            ModelState.Clear();
            ViewBag.SuccessMessage = "Successful Registration";
            return View("AddOrEdit", new User()); 
        }
    }
}

MVC/Views/User/AddOrEdit.cshtml
@model MVC.Models.User

@{
    ViewBag.Title = "User Registration";
    Layout = null;
}






<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />

    <style>

        a {
            text-decoration: none;
        }

        body {
            margin-top: 0;
            margin-left: 0;
        }
        /* Split the screen in half */
        .split {
            position: fixed;
            z-index: 1;
            top: 0;
            overflow-x: hidden;
        }

        .Top {
            z-index: 3;
            width: 100%;
            height: 10%;
            position: fixed;
            background: greenyellow;
        }

        /* Control the left side */
        .Nav {
            z-index: 2;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            left: 0;
            width: 13%;
            height: 100%;
            background-color: #111;
            margin-top: 3em;
            color: white;
        }

        .Nav_Head {
        }

        .Nav_Action_List {
            list-style: none;
        }


        /* Control the right side */
        .Content {
            display: flex;
            align-items: center;
            justify-content: center;
            float: left;
            width: 100%;
            right: 0;
            height: 100%;
            background-color: dimgrey;
        }

        .Content_table {
            background: #454545;
            width: max-content;
        }
    </style>
    <title>Index</title>
</head>
<body>

    <div class="Top">

        <h1>Dashboard</h1>

    </div>


    <div class="Nav split">
        <div class="Nav_Head">
            <h3>Welcome Dino</h3>
            @*<h3> Welcome @Session["userName"].ToString()</h3>*@
        </div>
        <div class="Nav_Action">


            <ul class="Nav_Action_List">
                <li><a href="@Url.Action("Index","Bug")"><h3>View Bug Report</h2></a></li>
                <li><a href="@Url.Action("Regist","Home")"><h3>Register</h3></a></li>
                <li><a href="@Url.Action("LogOut","Login")"><h3>Log Out</h3></a></li>
            </ul>




        </div>




    </div>

    <div class="Content split">



        <h2>User Registration</h2>


        @using (Html.BeginForm("AddOrEdit", "User", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @*<h4>User</h4>*@
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.isAdmin, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.isAdmin)
                            @Html.ValidationMessageFor(model => model.isAdmin, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Submit" class="btn btn-default" />
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-2">
                        <label class="label-success">@ViewBag.SuccessMessage</label>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-2">
                        <label class="label-danger">@ViewBag.DuplicateMessage</label>
                    </div>
                </div>
            </div>
        }

        @*<div>
            @Html.ActionLink("Back to List", "Index")
        </div>*@

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }




    </div>
</body>
</html>