MVC/Controllers/BugController.cs
using System;
using System.Collections.Generic;

using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC.Data;
using MVC.Models;

namespace MVC.Controllers
{
    public class BugController : Controller
    {
        private BugDatabaseEntities1 db = new BugDatabaseEntities1();



        
        // GET: Bug
        public ActionResult Index()
        {

            calcount(); //Get Total Count of Sql Data
            calHighRisk();

            var sqlDataList = Fetch();

            
            

            //var sqlData = FetchOne();

            return View("Index", sqlDataList);



            //return View(db.Table_1.ToList());
        }

      


        public ActionResult SearchButtonHandle(int id)
        {

            calcount(); //Get Total Count of Sql Data

            SqlFetch data = new SqlFetch();

            Table_1 obj = data.FetchOne(id);

            

            return View("Search", obj);

        }

        [HttpPost]
        public ActionResult SearchButtonHandle(FormCollection form)
        {

            ViewBag.test = form["SearchInput"];

            SqlFetch data = new SqlFetch();

            int numericValue;

            if (int.TryParse(ViewBag.test, out numericValue))
            {
                Table_1 obj = data.FetchOne(Int32.Parse(ViewBag.test));
                return View("Search", obj);

            }
            else
            {

                List<Table_1> list = new List<Table_1>();
                return View("Index", list);
            }

            



           

        }


        // GET: Bug/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Table_1 table_1 = db.Table_1.Find(id);
            if (table_1 == null)
            {
                return HttpNotFound();
            }
            return View(table_1);
        }

        // GET: Bug/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Bug/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Date,Bug_Level")] Table_1 table_1)
        {
            if (ModelState.IsValid)
            {
                db.Table_1.Add(table_1);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(table_1);
        }

        // GET: Bug/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Table_1 table_1 = db.Table_1.Find(id);
            if (table_1 == null)
            {
                return HttpNotFound();
            }
            return View(table_1);
        }

        // POST: Bug/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Date")] Table_1 table_1)
        {
            if (ModelState.IsValid)
            {
                db.Entry(table_1).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(table_1);
        }

        // GET: Bug/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Table_1 table_1 = db.Table_1.Find(id);
            if (table_1 == null)
            {
                return HttpNotFound();
            }
            return View(table_1);
        }

        // POST: Bug/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Table_1 table_1 = db.Table_1.Find(id);
            db.Table_1.Remove(table_1);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        public void calcount()
        {
            ViewBag.Count = db.Table_1.Count();
            
            
        }

        public void calHighRisk()
        {

            SqlFetch data = new SqlFetch();


            ViewBag.AmtHR = data.FetchHRAmt();
        }

        public List<Table_1> Fetch()
        {
            List<Table_1> dataObject = new List<Table_1>();

            SqlFetch data = new SqlFetch();

            dataObject = data.Fetch();

            return dataObject;
        }


        


    }
}

MVC/Controllers/ChartController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC.Models;

namespace MVC.Controllers
{
    public class ChartController : Controller
    {
        private BugDatabaseEntities1 db = new BugDatabaseEntities1();
        //IAgentService service = null;

        // GET: Chart
        public ActionResult Index()
        {
            
            return View();
        }

        public ActionResult BarChart()
        {
            return View();
        }

        // GET: Chart/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Table_1 table_1 = db.Table_1.Find(id);
            if (table_1 == null)
            {
                return HttpNotFound();
            }
            return View(table_1);
        }

        // GET: Chart/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Chart/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Date")] Table_1 table_1)
        {
            if (ModelState.IsValid)
            {
                db.Table_1.Add(table_1);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(table_1);
        }

        // GET: Chart/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Table_1 table_1 = db.Table_1.Find(id);
            if (table_1 == null)
            {
                return HttpNotFound();
            }
            return View(table_1);
        }

        // POST: Chart/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Date")] Table_1 table_1)
        {
            if (ModelState.IsValid)
            {
                db.Entry(table_1).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(table_1);
        }

        // GET: Chart/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Table_1 table_1 = db.Table_1.Find(id);
            if (table_1 == null)
            {
                return HttpNotFound();
            }
            return View(table_1);
        }

        // POST: Chart/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Table_1 table_1 = db.Table_1.Find(id);
            db.Table_1.Remove(table_1);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC/Views/Bug/Create.cshtml
@model MVC.Models.Table_1

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Table_1</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC/Views/Bug/Delete.cshtml
@model MVC.Models.Table_1

@{
    ViewBag.Title = "Delete";

    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <style>

        a {
            text-decoration: none;
        }

        body {
            margin-top: 0;
            margin-left: 0;
        }
        /* Split the screen in half */
        .split {
            position: fixed;
            z-index: 1;
            top: 0;
            overflow-x: hidden;
        }

        .Top {
            z-index: 3;
            width: 100%;
            height: 10%;
            position: fixed;
            background: greenyellow;
        }

        /* Control the left side */
        .Nav {
            z-index: 2;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            left: 0;
            width: 13%;
            height: 100%;
            background-color: #111;
            margin-top: 3em;
            color: white;
        }

        .Nav_Head {
        }

        .Nav_Action_List {
            list-style: none;
        }


        /* Control the right side */
        .Content {
            display: flex;
            align-items: center;
            justify-content: center;
            float: left;
            width: 100%;
            right: 0;
            height: 100%;
            background-color: dimgrey;
        }
    </style>
    <title>Index</title>
</head>
<body>

    <div class="Top">

        <h1>Dashboard</h1>

    </div>


    <div class="Nav split">
        <div class="Nav_Head">
            <h3>Welcome Dino</h3>
            @*<h3> Welcome @Session["userName"].ToString()</h3>*@
        </div>
        <div class="Nav_Action">


            <ul class="Nav_Action_List">
                <li><a href="@Url.Action("Index","Bug")"><h3>View Bug Report</h2></a></li>
                <li><a href="@Url.Action("Regist","Home")"><h3>Register</h3></a></li>
                <li><a href="@Url.Action("LogOut","Login")"><h3>Log Out</h3></a></li>
            </ul>




        </div>




    </div>

    <div class="Content split">

        <h2>Delete</h2>

        <h3>Are you sure you want to delete this?</h3>
        <div>
            <h4>Table_1</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Date)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Date)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Bug_Level)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Bug_Level)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" /> |
                    @Html.ActionLink("Back to List", "Index")
                </div>
            }
        </div>


    </div>
</body>
</html>

MVC/Views/Bug/Details.cshtml
@model MVC.Models.Table_1

@{
    ViewBag.Title = "Details";
    Layout = null;
}



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <style>

        a {
            text-decoration: none;
        }

        body {
            margin-top: 0;
            margin-left: 0;
        }
        /* Split the screen in half */
        .split {
            position: fixed;
            z-index: 1;
            top: 0;
            overflow-x: hidden;
        }

        .Top {
            z-index: 3;
            width: 100%;
            height: 10%;
            position: fixed;
            background: greenyellow;
        }

        /* Control the left side */
        .Nav {
            z-index: 2;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            left: 0;
            width: 13%;
            height: 100%;
            background-color: #111;
            margin-top: 3em;
            color: white;
        }

        .Nav_Head {
        }

        .Nav_Action_List {
            list-style: none;
        }


        /* Control the right side */
        .Content {
            display: flex;
            align-items: center;
            justify-content: center;
            float: left;
            width: 100%;
            right: 0;
            height: 100%;
            background-color: dimgrey;
        }
    </style>
    <title>Index</title>
</head>
<body>

    <div class="Top">

        <h1>Dashboard</h1>

    </div>


    <div class="Nav split">
        <div class="Nav_Head">
            <h3>Welcome Dino</h3>
            @*<h3> Welcome @Session["userName"].ToString()</h3>*@
        </div>
        <div class="Nav_Action">


            <ul class="Nav_Action_List">
                <li><a href="@Url.Action("Index","Bug")"><h3>View Bug Report</h2></a></li>
                <li><a href="@Url.Action("Regist","Home")"><h3>Register</h3></a></li>
                <li><a href="@Url.Action("LogOut","Login")"><h3>Log Out</h3></a></li>
            </ul>




        </div>




    </div>

    <div class="Content split">

        <h2>Details</h2>

        <div>
            <h4>Table_1</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Date)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Date)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Bug_Level)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Bug_Level)
                </dd>



            </dl>
        </div>
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
            @Html.ActionLink("Back to List", "Index")
        </p>


    </div>
</body>
</html>

MVC/Views/Bug/Edit.cshtml
@model MVC.Models.Table_1

@{
    ViewBag.Title = "Edit";
    Layout = null;
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />

    <style>

        a {
            text-decoration: none;
        }

        body {
            margin-top: 0;
            margin-left: 0;
        }
        /* Split the screen in half */
        .split {
            position: fixed;
            z-index: 1;
            top: 0;
            overflow-x: hidden;
        }

        .Top {
            z-index: 3;
            width: 100%;
            height: 10%;
            position: fixed;
            background: greenyellow;
        }

        /* Control the left side */
        .Nav {
            z-index: 2;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            left: 0;
            width: 13%;
            height: 100%;
            background-color: #111;
            margin-top: 3em;
            color: white;
        }

        .Nav_Head {
        }

        .Nav_Action_List {
            list-style: none;
        }


        /* Control the right side */
        .Content {
            display: flex;
            align-items: center;
            justify-content: center;
            float: left;
            width: 100%;
            right: 0;
            height: 100%;
            background-color: dimgrey;
        }

        .Content_table {
            background: #454545;
            width: max-content;
        }
    </style>
    <title>Index</title>
</head>
<body>

    <div class="Top">

        <h1>Dashboard</h1>

    </div>


    <div class="Nav split">
        <div class="Nav_Head">
            <h3>Welcome Dino</h3>
            @*<h3> Welcome @Session["userName"].ToString()</h3>*@
        </div>
        <div class="Nav_Action">


            <ul class="Nav_Action_List">
                <li><a href="@Url.Action("Index","Bug")"><h3>View Bug Report</h2></a></li>
                <li><a href="@Url.Action("Regist","Home")"><h3>Register</h3></a></li>
                <li><a href="@Url.Action("LogOut","Login")"><h3>Log Out</h3></a></li>
            </ul>




        </div>




    </div>

    <div class="Content split">



        @*<h2>Edit</h2>*@


        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Table_1</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
                @Html.LabelFor(model => model.Bug_Level, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Bug_Level, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Bug_Level, "", new { @class = "text-danger" })
                </div>
            </div>*@

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }




    </div>
</body>
</html>

MVC/Views/Bug/Index.cshtml
@model IEnumerable<MVC.Models.Table_1>
@Model MVC.Models.Table_1

@{
    ViewBag.Title = "Index";
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Teko" rel="stylesheet">
    <style>

        a {
            text-decoration: none;
        }

        body {
            margin-top: 0;
            margin-left: 0;
            font-family: 'Teko', serif;
        }
        /* Split the screen in half */
        .split {
            position: fixed;
            z-index: 1;
            top: 0;
            overflow-x: hidden;
        }

        .Top {
            z-index: 3;
            width: 100%;
            height: 10%;
            position: fixed;
            background: greenyellow;
            padding-left: 3em;
            padding-top: 1em;
            padding-bottom: 1em;
        }

            .Top div {
                float: left;
                clear: none;
            }

            .Top h1 {
                font-size: 40px;
            }

        .Top_Function {
            display: inline-block;
        }

        /* Control the left side */
        .Nav {
            z-index: 2;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            left: 0;
            width: 8%;
            height: 100%;
            background-color: #111;
            margin-top: 3em;
            color: white;
        }

        .Nav_Action {
            display: flex;
            left: 10%;
            margin-right: 2em;
        }



        .Nav_Action_List {
            list-style: none;
            font-size: 20px;
        }

            .Nav_Action_List a {
                color: #dbdbdb
            }


        /* Control the right side */
        .Content {
            display: flex;
            align-items: center;
            justify-content: right;
            float: left;
            width: 100%;
            right: 0;
            height: 100%;
            background-color: dimgrey;
        }

        .Content_table {
            /*float:left;
            clear:none;*/
            position: absolute;
            left: 20%;
            top: 15%;
        }

        .Content_table_create {
            /*  transform();*/
        }


        .Content_table_container {
            /*position: relative;*/
            /*top: 50%;
            left: -200%;*/
            /*transform: translate(-50%, -50%);*/
        }

        table {
            width: max-content;
            border-collapse: collapse;
            overflow: hidden;
            /*box-shadow: 0 0 20px rgba(0,0,0,0.1);*/
        }

        th,
        td {
            padding: 15px;
            background-color: rgba(255,255,255,0.2);
            color: #fff;
        }

        th {
            text-align: left;
        }

        thead th {
            background-color: #0b049c
        }

        tbody tr:hover {
            background-color: rgba(255,255,255,0.3);
        }

        tbody td {
            position: relative;
        }

        /* tbody td:before{
            content: "";
            position: absolute;
            left: 0;
            right: 0;
            top: -9999px;
            bottom: -9999px;
            background-color: rgba(255,255,255,0.2);
            z-index: -1;
        }*/


    </style>

</head>
<body>

    <div class="Top">

        <div class="Top_Head">

            <h1>Bug Tracker</h1>

        </div>



        <div class="Top_Function" style="float:left;">

            <div>

                <h3>Welcome Dino</h3>



                @*<h3> Welcome @Session["userName"].ToString()</h3>*@
            </div>

            <div style="margin-left:.3em;">
                <a href="@Url.Action("LogOut","Login")"><h3>Log Out</h3></a>
            </div>



        </div>

    </div>


    <div class="Nav split">

        <div class="Nav_Action">


            <ul class="Nav_Action_List">
                <li><a href="@Url.Action("Index","Chart")"><h3>Chart</h2></a></li>

            </ul>




        </div>




    </div>

    <div class="Content split">

        <div class="Content_table">

            <div class="Content_table_create">

                <p>
                    @Html.ActionLink("Create New", "Create")
                </p>


            </div>
            <div class="Content_data">
                <label>@ViewBag.Count</label>



                @using (Html.BeginForm("SearchButtonHandle", "Bug", new { id = ViewBag.Count }))
                {

                    <input id="Name" name="SearchInput" type="text" value="" />
                    <input type="submit" value="Search" />
                }

               
            </div>

            <label>@ViewBag.AmtHR</label>

            <div class="Content_search">

            </div>


            <div class="Content_table_container">

                <table class="table">

                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Date)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Bug_Level)
                            </th>
                            <th></th>
                        </tr>

                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Date)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Bug_Level)
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                                </td>
                            </tr>
                        }
                    </tbody>




                </table>

            </div>



        </div>







    </div>
</body>
</html>

MVC/Views/Bug/Search.cshtml
@model MVC.Models.Table_1

@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>

<div>
    <h4>Table_1</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bug_Level)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bug_Level)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>